# Generated by Django 6.1 on 2026-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
