# Generated by Django 6.1 on 2026-08-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_vehicle_image_vehicle_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
